import { useState } from 'react'
import { api, type ReportMatch, type TournamentReport } from '../lib/api'
import { useApi } from '../lib/useApi'
import { Card, Empty, ErrorNote, Loading, StatTile } from '../components/ui'

const MODEL_NAMES: Record<string, string> = {
  elo: 'Elo + draw rate',
  dixon_coles: 'Dixon-Coles',
  ml: 'Gradient boosting',
  ensemble: 'Ensemble',
}
const OUTCOME_LABEL = ['Home win', 'Draw', 'Away win']

export default function ReportCardPage() {
  const { data, error, loading } = useApi(() => api.tournamentReports(), [])
  const [key, setKey] = useState<string | null>(null)

  if (error) return <ErrorNote message={error} />
  if (loading || !data) return <Loading />
  const reports = data.reports
  if (!reports.length) {
    return <Empty text="No tournament reports yet — they are generated by the ETL refresh." />
  }
  const report = reports.find((r) => r.key === key) ?? reports[0]
  const ens = report.models.ensemble

  return (
    <div className="grid gap-4">
      <div className="flex flex-wrap items-center gap-2">
        {reports.length > 1 && (
          <select aria-label="Tournament" className="card px-3 py-1.5 text-sm"
            value={report.key} onChange={(e) => setKey(e.target.value)}>
            {reports.map((r) => <option key={r.key} value={r.key}>{r.name}</option>)}
          </select>
        )}
        <span className="text-sm font-semibold">{report.name}</span>
        <span className="text-xs" style={{ color: 'var(--muted)' }}>
          Walk-forward: trained only on data before {report.since} · updated {report.computed_at}
        </span>
      </div>

      <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
        <StatTile label="Matches evaluated" value={String(report.n_matches)}
          sub={`W/D/L split ${report.outcome_split.join('/')}`} />
        <StatTile label="Ensemble accuracy" value={`${(ens.accuracy * 100).toFixed(1)}%`}
          sub="3-way result picked correctly" />
        <StatTile label="Ensemble Brier" value={ens.brier.toFixed(3)}
          sub={`Baseline ${report.baselines.frequency_brier.toFixed(3)} · 0 is perfect`} />
        <StatTile label="Best model"
          value={MODEL_NAMES[bestModel(report)] ?? bestModel(report)}
          sub="Lowest Brier score" />
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card title="Model comparison">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs" style={{ color: 'var(--muted)' }}>
                <th className="py-1">Model</th>
                <th className="py-1 text-right">Accuracy</th>
                <th className="py-1 text-right">Brier ↓</th>
              </tr>
            </thead>
            <tbody>
              {(['elo', 'dixon_coles', 'ml', 'ensemble'] as const)
                .filter((m) => report.models[m])
                .map((m) => (
                  <tr key={m} className="border-t" style={{ borderColor: 'var(--grid)' }}>
                    <td className={`py-1.5 ${m === 'ensemble' ? 'font-semibold' : ''}`}>
                      {MODEL_NAMES[m]}
                    </td>
                    <td className="py-1.5 text-right tabular">
                      {(report.models[m].accuracy * 100).toFixed(1)}%
                    </td>
                    <td className="py-1.5 text-right tabular">{report.models[m].brier.toFixed(3)}</td>
                  </tr>
                ))}
            </tbody>
          </table>
        </Card>

        <Card title="Calibration — when we say X%, does it happen X% of the time?">
          <table className="w-full text-sm">
            <thead>
              <tr className="text-left text-xs" style={{ color: 'var(--muted)' }}>
                <th className="py-1">Favourite probability</th>
                <th className="py-1 text-right">Predicted</th>
                <th className="py-1 text-right">Actual</th>
                <th className="py-1 text-right">n</th>
              </tr>
            </thead>
            <tbody>
              {report.calibration.map((c) => (
                <tr key={c.bucket} className="border-t" style={{ borderColor: 'var(--grid)' }}>
                  <td className="py-1.5">{c.bucket}</td>
                  <td className="py-1.5 text-right tabular">{(c.predicted * 100).toFixed(0)}%</td>
                  <td className="py-1.5 text-right tabular font-semibold">
                    {(c.actual * 100).toFixed(0)}%
                  </td>
                  <td className="py-1.5 text-right tabular" style={{ color: 'var(--muted)' }}>{c.n}</td>
                </tr>
              ))}
            </tbody>
          </table>
          <p className="mt-2 text-xs" style={{ color: 'var(--muted)' }}>
            Small buckets swing a lot — treat rows with n &lt; 15 as indicative only.
          </p>
        </Card>
      </div>

      <Card title="Every match, every forecast">
        <ul className="divide-y" style={{ borderColor: 'var(--grid)' }}>
          {[...report.matches].reverse().map((m, i) => <MatchRow key={i} m={m} />)}
        </ul>
      </Card>
    </div>
  )
}

function bestModel(r: TournamentReport): string {
  return Object.entries(r.models).sort((a, b) => a[1].brier - b[1].brier)[0][0]
}

function MatchRow({ m }: { m: ReportMatch }) {
  const correct = m.predicted === m.outcome
  const [w, d, l] = m.probs
  return (
    <li className="flex flex-wrap items-center gap-x-3 gap-y-1 py-2 text-sm">
      <span className="w-20 shrink-0 text-xs tabular" style={{ color: 'var(--muted)' }}>{m.date}</span>
      <span className="w-40 truncate text-right sm:w-48">{m.home}</span>
      <span className="tabular rounded px-2 py-0.5 text-xs font-semibold"
        style={{ background: 'var(--page)', border: '1px solid var(--border)' }}>
        {m.home_score} – {m.away_score}
      </span>
      <span className="w-40 truncate sm:w-48">{m.away}</span>
      <span className="flex h-3 w-28 overflow-hidden rounded-sm" style={{ gap: 1 }}
        title={`W ${(w * 100).toFixed(0)}% / D ${(d * 100).toFixed(0)}% / L ${(l * 100).toFixed(0)}%`}
        aria-label={`Forecast: home win ${(w * 100).toFixed(0)}%, draw ${(d * 100).toFixed(0)}%, away win ${(l * 100).toFixed(0)}%`}>
        <span style={{ width: `${w * 100}%`, background: 'var(--series-1)' }} />
        <span style={{ width: `${d * 100}%`, background: 'var(--series-3)' }} />
        <span style={{ width: `${l * 100}%`, background: 'var(--series-6)' }} />
      </span>
      <span className="text-xs tabular" style={{ color: 'var(--ink-2)' }}>
        {(Math.max(w, d, l) * 100).toFixed(0)}% {OUTCOME_LABEL[m.predicted]}
      </span>
      <span className="font-semibold" aria-label={correct ? 'correct' : 'wrong'}
        style={{ color: correct ? 'var(--good)' : 'var(--series-6)' }}>
        {correct ? '✓' : '✗'}
      </span>
    </li>
  )
}
